/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import { PUBLIC_AWS_COGNITO_REGION, PUBLIC_AWS_COGNITO_USERPOOL, PUBLIC_AWS_OAUTH_DOMAIN, PUBLIC_AWS_PROJECT_REGION, PUBLIC_AWS_USERPOOL_WEB_CLIENT_ID } from "$env/static/public";


const awsmobile = {
    "aws_project_region": PUBLIC_AWS_PROJECT_REGION,
    "aws_cognito_region": PUBLIC_AWS_COGNITO_REGION,
    "aws_user_pools_id": PUBLIC_AWS_COGNITO_USERPOOL,
    "aws_user_pools_web_client_id": PUBLIC_AWS_USERPOOL_WEB_CLIENT_ID,
    "oauth": {
        "domain": PUBLIC_AWS_OAUTH_DOMAIN
    },
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 10,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
};


export default awsmobile;
